### ISSUE TITLE
main.js from Terser Error: Call retries were exceeded

### ISSUE THREAD

**Issue by parthkakadiya** [brydko/jhipster-universal#3]
Hi Brydko,

First of all thank you for providing example code of the Jhipster-universal integration.  

since, few month i am trying to implement angular universal on my existing Jhipster based Microservice architecture application. I have followed your first version of the Jhipster-universal integration project to implement universal on my application. But I am stuck at one error of webpack-terser-plugin:

Hash: ec4bef88fb0ac02e1dd6
Time: 231281ms
Built at: 07/29/2020 10:52:21 AM
  Asset      Size  Chunks  Chunk Names
main.js  57.7 MiB       0  main
Entrypoint main = main.js
chunk    {0} main.js (main) 56.1 MiB [entry] [rendered]

WARNING in ./src/main/webapp/app/pages/view_betriebe/viewbetriebe.component.scss
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(494:3) Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
WARNING in ./src/main/webapp/app/pages/public-betrieb-view/public-betrieb-view.component.scss
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(494:3) Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
WARNING in ./src/main/webapp/app/pages/production-view/production-view.component.scss
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(565:3) Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
WARNING in ./src/main/webapp/app/pages/public-production-view/public-production-view.component.scss
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(565:3) Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
**ERROR in main.js from Terser
Error: Call retries were exceeded**
    at ChildProcessWorker.initialize (C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\workers\ChildProcessWorker.js:191:21)
    at ChildProcessWorker._onExit (C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\workers\ChildProcessWorker.js:268:12)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

I have searched on internet about this issue and tried some solution as well but doesn't worked out. always stop at same error. Like you can see from compile message bundle is generated but don't know ow to fix this last error.  

i provide some important files for the Universal .
[Jhipster-angular important files.zip](https://github.com/brydko/jhipster-universal/files/4993835/Jhipster-angular.important.files.zip)

 could you please have a look. I am very thankful to you.

**Comment by brydko** [comment]
Hello @parthkakadiya 

Thanks for trying out the example project.


I'm going to assume that the (non SSR) production build runs ok with no errors. If this is the case, then some changes should be made to the SSR custom webpack configuration. Before that, you may try the following change:

In angular.json replace `"builder": "@angular-builders/custom-webpack:server"` by `"builder": "@angular-devkit/build-angular:server"` and delete `"customWebpackConfig"` so it looks like this:

```json
"server": {
  "builder": "@angular-devkit/build-angular:server",
  "options": {
    "outputPath": "target/classes/static/server",
    "main": "server.ts",
    "tsConfig": "tsconfig.server.json"
  },
  "configurations": {
     "production": {
       "outputHashing": "media",
       "sourceMap": false,
       "optimization": true
     }
  }
}
```

In case this change makes no difference, please provide me the offending line from any of your scss files so I can reproduce the error in my setup.

Cheers.

**Comment by parthkakadiya** [comment]
HI @brydko 

Thanks a lot for you reply and help. I am sorry if i have used wrong place to address my issue.

To be honest, I am new to the Jhipster. 

I applied your given changes but it still giving same error. I have eliminated css error.

Also, do you have any idea what is the cause of this error?

current compilation message:

yarn run v1.22.0
$ ng build --prod && ng run jhipster:server:production
Warning: Entry point 'agm-direction' contains deep imports into 'C:/Users/eKultur/Documents/gateway-angular-8/toshiba/node_modules/@agm/core/services/google-maps-types'. This is probably not a problem, but may cause the compilation of entry points to be out of orde
r.
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {26} polyfills-es2015.81a7f57eaf187ad55408.js (polyfills) 36.8 kB [initial] [rendered]
chunk {27} polyfills-es5.b08420b63d4bde2a62c9.js (polyfills-es5) 130 kB [initial] [rendered]
chunk {0} common-es2015.3f67913466dd56f6beed.js (common) 8.5 kB  [rendered]
chunk {0} common-es5.3f67913466dd56f6beed.js (common) 10.5 kB  [rendered]
chunk {2} 2-es2015.c956dc7626658b8c6c86.js () 14.6 kB  [rendered]
chunk {2} 2-es5.c956dc7626658b8c6c86.js () 16.9 kB  [rendered]
chunk {3} 3-es2015.5c451eb55c79c2229938.js () 52.9 kB  [rendered]
chunk {3} 3-es5.5c451eb55c79c2229938.js () 53.6 kB  [rendered]
chunk {6} 6-es2015.9d8644f72de1d845abae.js () 39.5 kB  [rendered]
chunk {6} 6-es5.9d8644f72de1d845abae.js () 42.5 kB  [rendered]
chunk {5} 5-es2015.e9c0590edba3d64ad3f7.js () 945 kB  [rendered]
chunk {5} 5-es5.e9c0590edba3d64ad3f7.js () 1020 kB  [rendered]
chunk {7} 7-es2015.31ea275077d00f288c0e.js () 70.8 kB  [rendered]
chunk {7} 7-es5.31ea275077d00f288c0e.js () 70.8 kB  [rendered]
chunk {4} 4-es2015.916ce094eef01f220074.js () 2.53 kB  [rendered]
chunk {4} 4-es5.916ce094eef01f220074.js () 3.19 kB  [rendered]
chunk {8} 8-es2015.b6934da689dededce4bf.js () 11.2 kB  [rendered]
chunk {8} 8-es5.b6934da689dededce4bf.js () 12.8 kB  [rendered]
chunk {9} 9-es2015.d79dda424e3a3e6b772e.js () 42.6 kB  [rendered]
chunk {9} 9-es5.d79dda424e3a3e6b772e.js () 56.7 kB  [rendered]
chunk {11} 11-es2015.ae4f1f3e0aae80a445b3.js () 2.75 MB  [rendered]
chunk {11} 11-es5.ae4f1f3e0aae80a445b3.js () 2.76 MB  [rendered]
chunk {12} 12-es2015.0c9c6523e6c0528d8879.js () 21.3 kB  [rendered]
chunk {12} 12-es5.0c9c6523e6c0528d8879.js () 23.4 kB  [rendered]
chunk {14} 14-es2015.f970aa531ac3104d7975.js () 22.7 kB  [rendered]
chunk {14} 14-es5.f970aa531ac3104d7975.js () 25.9 kB  [rendered]
chunk {15} 15-es2015.d8b86a679e1c9e5c121b.js () 2.97 MB  [rendered]
chunk {15} 15-es5.d8b86a679e1c9e5c121b.js () 2.97 MB  [rendered]
chunk {17} 17-es2015.a97eb20a28624e682201.js () 435 kB  [rendered]
chunk {17} 17-es5.a97eb20a28624e682201.js () 441 kB  [rendered]
chunk {16} 16-es2015.952317658fc1e9a6cb5b.js () 11.1 kB  [rendered]
chunk {16} 16-es5.952317658fc1e9a6cb5b.js () 12.2 kB  [rendered]
chunk {18} 18-es2015.afe4f9a902db810a944f.js () 2.22 MB  [rendered]
chunk {18} 18-es5.afe4f9a902db810a944f.js () 2.23 MB  [rendered]
chunk {19} 19-es2015.3c65a38c0b112403d3d4.js () 191 kB  [rendered]
chunk {19} 19-es5.3c65a38c0b112403d3d4.js () 197 kB  [rendered]
chunk {20} 20-es2015.61b66cd89604e9dc0d6a.js () 324 kB  [rendered]
chunk {20} 20-es5.61b66cd89604e9dc0d6a.js () 330 kB  [rendered]
chunk {21} 21-es2015.e7576b4e126534aeeceb.js () 122 kB  [rendered]
chunk {21} 21-es5.e7576b4e126534aeeceb.js () 124 kB  [rendered]
chunk {22} 22-es2015.dab0d3a1f12f9b4d92d7.js () 2.67 kB  [rendered]
chunk {22} 22-es5.dab0d3a1f12f9b4d92d7.js () 3.14 kB  [rendered]
chunk {23} 23-es2015.60d799ebc9e0cab462b0.js () 87.8 kB  [rendered]
chunk {23} 23-es5.60d799ebc9e0cab462b0.js () 90.4 kB  [rendered]
chunk {24} 24-es2015.18af8c2bfab9be231c23.js () 2.91 MB  [rendered]
chunk {24} 24-es5.18af8c2bfab9be231c23.js () 2.91 MB  [rendered]
chunk {29} 29-es2015.009bb97165050b65a354.js () 156 kB  [rendered]
chunk {29} 29-es5.009bb97165050b65a354.js () 160 kB  [rendered]
chunk {30} 30-es2015.4de69aeff5ce4ab256fb.js () 41.8 kB  [rendered]
chunk {30} 30-es5.4de69aeff5ce4ab256fb.js () 43.4 kB  [rendered]
chunk {32} 32-es2015.963837a6a36112daba1d.js () 1.62 MB  [rendered]
chunk {32} 32-es5.963837a6a36112daba1d.js () 1.62 MB  [rendered]
chunk {31} 31-es2015.fee37445f5506250cf32.js () 2.73 MB  [rendered]
chunk {31} 31-es5.fee37445f5506250cf32.js () 2.73 MB  [rendered]
chunk {33} 33-es2015.aaaa7ef4c2a69569d61f.js () 98.6 kB  [rendered]
chunk {33} 33-es5.aaaa7ef4c2a69569d61f.js () 99.5 kB  [rendered]
chunk {34} 34-es2015.3f256efae953b7a0896a.js () 99.7 kB  [rendered]
chunk {34} 34-es5.3f256efae953b7a0896a.js () 103 kB  [rendered]
chunk {36} 36-es2015.7d91e9b335033e1ccff9.js () 106 kB  [rendered]
chunk {36} 36-es5.7d91e9b335033e1ccff9.js () 110 kB  [rendered]
chunk {35} 35-es2015.50c3d2f50030c8274aca.js () 2.87 MB  [rendered]
chunk {35} 35-es5.50c3d2f50030c8274aca.js () 2.87 MB  [rendered]
chunk {38} 38-es2015.ef1f9272b13bf15660f1.js () 63 kB  [rendered]
chunk {38} 38-es5.ef1f9272b13bf15660f1.js () 64.5 kB  [rendered]
chunk {37} 37-es2015.426792dd47d6d7116e10.js () 64 kB  [rendered]
chunk {37} 37-es5.426792dd47d6d7116e10.js () 67.1 kB  [rendered]
chunk {39} 39-es2015.8a0ba9dfdb976afb82da.js () 69.6 kB  [rendered]
chunk {39} 39-es5.8a0ba9dfdb976afb82da.js () 72.6 kB  [rendered]
chunk {40} 40-es2015.4a4181c12acac8a7d35e.js () 66 kB  [rendered]
chunk {40} 40-es5.4a4181c12acac8a7d35e.js () 67.1 kB  [rendered]
chunk {41} 41-es2015.8bb9151cda5348c662bd.js () 23.1 kB  [rendered]
chunk {41} 41-es5.8bb9151cda5348c662bd.js () 23.9 kB  [rendered]
chunk {42} 42-es2015.5e075e787d69a41ff78e.js () 26.5 kB  [rendered]
chunk {42} 42-es5.5e075e787d69a41ff78e.js () 27 kB  [rendered]
chunk {43} 43-es2015.dab33dbcdb112526da1d.js () 6.82 kB  [rendered]
chunk {43} 43-es5.dab33dbcdb112526da1d.js () 7.45 kB  [rendered]
chunk {45} 45-es2015.0508ead41d8522040cc1.js () 922 bytes  [rendered]
chunk {45} 45-es5.0508ead41d8522040cc1.js () 1.03 kB  [rendered]
chunk {44} 44-es2015.fb39480d56e9c97eccd6.js () 2.79 MB  [rendered]
chunk {44} 44-es5.fb39480d56e9c97eccd6.js () 2.79 MB  [rendered]
chunk {46} 46-es2015.4b012295ba55e61a09d6.js () 12.9 kB  [rendered]
chunk {46} 46-es5.4b012295ba55e61a09d6.js () 14 kB  [rendered]
chunk {48} 48-es2015.72e2af00e6eb0b78ca1c.js () 956 bytes  [rendered]
chunk {48} 48-es5.72e2af00e6eb0b78ca1c.js () 1.07 kB  [rendered]
chunk {47} 47-es2015.e35af1ca3e698498e4b0.js () 120 kB  [rendered]
chunk {47} 47-es5.e35af1ca3e698498e4b0.js () 124 kB  [rendered]
chunk {49} 49-es2015.7216e7693d3c558bff1c.js () 122 kB  [rendered]
chunk {49} 49-es5.7216e7693d3c558bff1c.js () 125 kB  [rendered]
chunk {51} 51-es2015.20da21114295c6dee86c.js () 296 kB  [rendered]
chunk {51} 51-es5.20da21114295c6dee86c.js () 300 kB  [rendered]
chunk {53} 53-es2015.dc2681d105af5d1e4564.js () 817 bytes  [rendered]
chunk {53} 53-es5.dc2681d105af5d1e4564.js () 954 bytes  [rendered]
chunk {52} 52-es2015.38ccdbbdd77eb9626828.js () 5.15 kB  [rendered]
chunk {52} 52-es5.38ccdbbdd77eb9626828.js () 5.67 kB  [rendered]
chunk {50} 50-es2015.89df3ae56813627e78f4.js () 102 kB  [rendered]
chunk {50} 50-es5.89df3ae56813627e78f4.js () 106 kB  [rendered]
chunk {54} 54-es2015.bc75de5171c87f9bf1de.js () 152 kB  [rendered]
chunk {54} 54-es5.bc75de5171c87f9bf1de.js () 154 kB  [rendered]
chunk {10} runtime-es2015.bd5f02ff08931896b8c3.js (runtime) 3.48 kB [entry] [rendered]
chunk {10} runtime-es5.bd5f02ff08931896b8c3.js (runtime) 3.48 kB [entry] [rendered]
chunk {1} 1-es2015.53969802f446ff06a733.js () 181 kB  [rendered]
chunk {1} 1-es5.53969802f446ff06a733.js () 183 kB  [rendered]
chunk {25} main-es2015.287c0e5d038632974bdf.js (main) 5.95 MB [initial] [rendered]
chunk {25} main-es5.287c0e5d038632974bdf.js (main) 6.13 MB [initial] [rendered]
chunk {13} 13-es2015.b4b86bd941b69cd2391d.js () 6.33 MB  [rendered]
chunk {13} 13-es5.b4b86bd941b69cd2391d.js () 6.48 MB  [rendered]
chunk {28} styles.85bde8d18583eab893d2.css (styles) 143 kB [initial] [rendered]
Date: 2020-08-04T13:33:53.722Z - Hash: e91fa0118801976b7b68 - Time: 372404ms

WARNING in budgets: Exceeded maximum budget for initial-es2015. Budget 2 MB was not met by 4.13 MB with a total of 6.13 MB.

WARNING in budgets: Exceeded maximum budget for initial-es5. Budget 2 MB was not met by 4.4 MB with a total of 6.4 MB.
Warning: Entry point 'agm-direction' contains deep imports into 'C:/Users/eKultur/Documents/gateway-angular-8/toshiba/node_modules/@agm/core/services/google-maps-types'. This is probably not a problem, but may cause the compilation of entry points to be out of orde
r.
92% chunk asset optimization TerserPluginFATAL ERROR: Ineffect
<--- Last few GCs --->

[4492:0000027ECC3E8F40]    33120 ms: Scavenge 2046.1 (2049.5) -> 2045.7 (2050.0) MB, 5.8 / 0.0 ms  (average mu = 0.133, current mu = 0.131) allocation failure
[4492:0000027ECC3E8F40]    33186 ms: Scavenge 2046.4 (2050.0) -> 2045.9 (2050.0) MB, 5.6 / 0.0 ms  (average mu = 0.133, current mu = 0.131) allocation failure
[4492:0000027ECC3E8F40]    33249 ms: Scavenge 2046.7 (2050.0) -> 2046.2 (2050.3) MB, 6.3 / 0.0 ms  (average mu = 0.133, current mu = 0.131) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF69A684DDD]
Security context: 0x01eadbc008d1 <JSObject>
    1: _(aka _) [0000039ED7F8E811] [C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:~1] [pc=000001B34D502E18](this=0x00ed8d3004b1 <undefined>,0
x02006ad83559 <String[#4]: punc>,0x006719920839 <String[#1]: )>,0x00ed8d3004b1 <undefined>)
 ...

ive mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200804.153558.4492.0.001.json
Node.js report completed
 1: 00007FF699A8363F napi_wrap+128063
 2: 00007FF699A22836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF699A234F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF69A239F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF69A222021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF69A0EE57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF69A0F97D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF69A0F62F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF69A0EBB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF69A0EA184 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF69A10B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF699E70C51 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __p
tr64+1665
13: 00007FF69A684DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 000001B34D502E18
FATAL ERROR: Ineffective mark-compacts near
<--- Last few GCs --->

[15768:000001FA3BDFAA20]    30702 ms: Scavenge 2046.3 (2049.5) -> 2045.8 (2050.0) MB, 6.0 / 0.0 ms  (average mu = 0.137, current mu = 0.137) allocation failure
[15768:000001FA3BDFAA20]    30767 ms: Scavenge 2046.5 (2050.0) -> 2046.1 (2050.0) MB, 6.0 / 0.0 ms  (average mu = 0.137, current mu = 0.137) allocation failure
[15768:000001FA3BDFAA20]    30833 ms: Scavenge 2046.8 (2050.0) -> 2046.3 (2050.3) MB, 5.9 / 0.0 ms  (average mu = 0.137, current mu = 0.137) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF69A684DDD]
    1: StubFrame [pc: 00007FF69A609455]
Security context: 0x029a683808d1 <JSObject>
    2: H [0000028A8DD04A21] [C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:~1] [pc=00000382FAF4D799](this=0x028a8dd04a61 <Object map = 000001
F812E8D3B9>,0x01e91ebc04b1 <undefined>)
    3: s(aka ...

 heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200804.153630.15768.0.001.json
Node.js report completed
 1: 00007FF699A8363F napi_wrap+128063
 2: 00007FF699A22836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF699A234F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF69A239F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF69A222021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF69A0EE57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF69A0F97D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF69A0F62F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF69A0EBB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF69A0EA184 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF69A10B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF699E70C51 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __p
tr64+1665
13: 00007FF69A684DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 00007FF69A609455 public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+40389
15: 00000382FAF4D799
FATAL ERROR: Ineffective mark-compacts near
<--- Last few GCs --->
) [11976:000001AF1BBC8430]    32505 ms: Mark-sweep 2047.6 (2050.5) -> 2047.1 (2050.8) MB, 1467.6 / 0.0 ms  (+ 77.2 ms in 9 steps since start of marking, biggest step 10.6 ms, walltime since start of marking 1548 ms) (average mu = 0.130, current mu = 0.002) [11976:0
00001AF1BBC8430]    33981 ms: Mark-sweep 2047.8 (2050.8) -> 2047.4 (2051.0) MB, 1382.7 / 0.0 ms  (+ 89.7 ms in 10 steps since start of marking, biggest step 22.7 ms, walltime since start of marking 1476 ms) (average mu = 0.067, current mu = 0.002)

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF69A684DDD]
    1: StubFrame [pc: 00007FF69A60B281]
Security context: 0x0315181c08d1 <JSObject>
    2: Ee(aka Ee) [00000258A4A052F1] [C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:~1] [pc=000003F6F2679CC2](this=0x0072e04804b1 <undefined>
)
    3: _e(aka _e) [00000258A4A05371] [C:\Users\eKul...

heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200804.153706.11976.0.001.json
Node.js report completed
 1: 00007FF699A8363F napi_wrap+128063
 2: 00007FF699A22836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF699A234F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF69A239F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF69A222021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF69A0EE57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF69A0F97D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF69A0F62F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF69A0EBB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF69A0EA184 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF69A10B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF699E70C51 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __p
tr64+1665
13: 00007FF69A684DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 00007FF69A60B281 public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+48113
15: 000003F6F2679CC2
FATAL ERROR: Ineffective mark-comp
<--- Last few GCs --->

[15324:000001651B4CBC20]    30808 ms: Scavenge 2043.0 (2048.0) -> 2042.1 (2048.5) MB, 5.2 / 0.0 ms  (average mu = 0.134, current mu = 0.132) allocation failure
[15324:000001651B4CBC20]    30815 ms: Scavenge 2043.6 (2048.5) -> 2042.7 (2053.5) MB, 5.0 / 0.0 ms  (average mu = 0.134, current mu = 0.132) allocation failure
[15324:000001651B4CBC20]    31175 ms: Scavenge 2046.2 (2053.8) -> 2044.1 (2050.3) MB, 6.3 / 0.0 ms  (average mu = 0.134, current mu = 0.132) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF69A684DDD]
Security context: 0x0270aecc08d1 <JSObject>
    1: _(aka _) [000002B872C40DA1] [C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:~1] [pc=000003D27EDFB14B](this=0x03a24d0c04b1 <undefined>,0
x03459d701a91 <String[#4]: punc>,0x0212f6960839 <String[#1]: )>,0x03a24d0c04b1 <undefined>)
 ...

acts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200804.153739.15324.0.001.json
Node.js report completed
 1: 00007FF699A8363F napi_wrap+128063
 2: 00007FF699A22836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF699A234F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF69A239F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF69A222021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF69A0EE57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF69A0F97D0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF69A0F62F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF69A0EBB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF69A0EA184 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF69A10B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF699E70C51 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __p
tr64+1665
13: 00007FF69A684DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 000003D27EDFB14B
Hash: 479935936d15c851bb28
Time: 218323ms
Built at: 08/04/2020 3:37:40 PM
  Asset      Size  Chunks  Chunk Names
main.js  56.8 MiB       0  main
Entrypoint main = main.js
chunk    {0} main.js (main) 55.9 MiB [entry] [rendered]

ERROR in main.js from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\workers\ChildProcessWorker.js:191:21)
    at ChildProcessWorker._onExit (C:\Users\eKultur\Documents\gateway-angular-8\toshiba\node_modules\@angular-devkit\build-angular\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\workers\ChildProcessWorker.js:268:12)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Cheers,
Parth
